package confluence_old

type AutoGenerated struct {
	ID                  string `json:"id"`
	Type                string `json:"type"`
	Status              string `json:"status"`
	Title               string `json:"title"`
	MacroRenderedOutput struct {
	} `json:"macroRenderedOutput"`
	Body struct {
		Storage struct {
			Value           string `json:"value"`
			Representation  string `json:"representation"`
			EmbeddedContent []any  `json:"embeddedContent"`
			Expandable      struct {
				Content string `json:"content"`
			} `json:"_expandable"`
		} `json:"storage"`
		Expandable struct {
			Editor              string `json:"editor"`
			AtlasDocFormat      string `json:"atlas_doc_format"`
			View                string `json:"view"`
			ExportView          string `json:"export_view"`
			StyledView          string `json:"styled_view"`
			Dynamic             string `json:"dynamic"`
			Editor2             string `json:"editor2"`
			AnonymousExportView string `json:"anonymous_export_view"`
		} `json:"_expandable"`
	} `json:"body"`
	Extensions struct {
		Position int `json:"position"`
	} `json:"extensions"`
	Expandable struct {
		Container           string `json:"container"`
		Metadata            string `json:"metadata"`
		Restrictions        string `json:"restrictions"`
		History             string `json:"history"`
		Version             string `json:"version"`
		Descendants         string `json:"descendants"`
		Space               string `json:"space"`
		ChildTypes          string `json:"childTypes"`
		SchedulePublishInfo string `json:"schedulePublishInfo"`
		Operations          string `json:"operations"`
		SchedulePublishDate string `json:"schedulePublishDate"`
		Children            string `json:"children"`
		Ancestors           string `json:"ancestors"`
	} `json:"_expandable"`
	Links struct {
		Editui     string `json:"editui"`
		Webui      string `json:"webui"`
		Context    string `json:"context"`
		Self       string `json:"self"`
		Tinyui     string `json:"tinyui"`
		Collection string `json:"collection"`
		Base       string `json:"base"`
	} `json:"_links"`
}
